from fastapi import Depends, HTTPException

from app.core.models import UserRole
from app.core.security import get_current_user


ROLE_PERMISSIONS: dict[str, set[str]] = {
    UserRole.SUPERADMIN.value: {
        "platform.manage",
        "platform.statistics.read",
        "audit.read_global",
    },
    UserRole.ADMIN.value: {
        "member.create",
        "member.read",
        "member.update",
        "member.validate",
        "member.suspend",
        "member.offboard",
        "member.outstanding.read",
        "meeting.create",
        "meeting.read",
        "meeting.update",
        "meeting.cancel",
        "meeting.close",
        "cotisation.create",
        "cotisation.read",
        "cotisation.update",
        "cotisation.validate",
        "cycle.create",
        "cycle.activate",
        "cycle.close",
        "parametres.update",
        "cash_account.read",
        "payment.create",
        "payment.validate",
        "payment.cancel",
        "payment.reverse",
        "penalite.create",
        "penalite.pay",
        "penalite.cancel",
        "sanction.create",
        "sanction.validate",
        "sanction.lift",
        "pret.create",
        "pret.approve",
        "pret.reject",
        "pret.repay",
        "tour.generate",
        "tour.pay",
        "decaissement.read",
        "decaissement.create",
        "decaissement.approve",
        "decaissement.reject",
        "tableau_bord.admin.read",
        "rapport.read",
        "rapport.export",
        "report.read",
        "audit.read",
    },
    UserRole.PRESIDENT.value: {
        "member.read",
        "member.update",
        "member.validate",
        "member.suspend",
        "member.offboard",
        "member.outstanding.read",
        "meeting.read",
        "meeting.update",
        "meeting.close",
        "cycle.close",
        "cotisation.read",
        "cash_account.read",
        "payment.reverse",
        "pret.approve",
        "pret.reject",
        "tour.pay",
        "decaissement.read",
        "decaissement.approve",
        "decaissement.reject",
        "tableau_bord.admin.read",
        "rapport.read",
        "rapport.export",
        "penalite.cancel",
        "sanction.validate",
        "sanction.lift",
        "report.read",
    },
    UserRole.SECRETAIRE.value: {
        "member.create",
        "member.read",
        "member.update",
        "meeting.create",
        "meeting.read",
        "meeting.update",
        "meeting.cancel",
        "meeting.close",
        "cycle.create",
        "cotisation.create",
        "cotisation.read",
        "cotisation.update",
        "document.create",
        "document.read",
        "penalite.create",
        "sanction.create",
        "tour.generate",
        "tableau_bord.admin.read",
        "rapport.read",
        "rapport.export",
    },
    UserRole.TRESORIER.value: {
        "cotisation.validate",
        "cotisation.create",
        "cotisation.read",
        "cotisation.update",
        "payment.create",
        "payment.validate",
        "payment.cancel",
        "penalite.create",
        "penalite.pay",
        "pret.create",
        "pret.repay",
        "tour.pay",
        "decaissement.read",
        "decaissement.create",
        "cash_account.read",
        "tableau_bord.admin.read",
        "rapport.read",
        "rapport.export",
        "financial_report.read",
        "member.outstanding.read",
    },
    UserRole.CENSEUR.value: {
        "member.read",
        "discipline.read",
        "discipline.manage",
        "penalite.create",
        "sanction.create",
        "sanction.lift",
    },
    UserRole.MEMBRE.value: {
        "member.read_own",
        "cotisation.read_own",
        "meeting.read",
        "payment.read_own",
        "loan.read_own",
        "pret.create",
        "tableau_bord.member.read",
        "notification.read_own",
    },
}


def has_permission(role: str | None, permission: str) -> bool:
    if not role:
        return False
    return permission in ROLE_PERMISSIONS.get(role, set())


def require_permission(permission: str):
    async def dep(current_user: dict = Depends(get_current_user)):
        if not has_permission(current_user.get("role"), permission):
            raise HTTPException(403, f"Permission requise : {permission}")
        return current_user

    return dep
